import * as React from 'react';
import { Link } from 'react-router-dom';
import * as classNames from 'classnames/bind';
import styles from './Vote.scss';
const cx = classNames.bind(styles);

export default class Home extends React.Component {
    render() {
        return (
            <div className={cx('Vote')}>
                <h2>#INSSAWIKI - Vote</h2>
                <div className={cx('line')} />
                <table>
                    <thead>
                    <td>No.</td>
                    <td>Buzzwords</td>
                    </thead>
                    <tbody>
                    <tr>
                        <td>01</td>
                        <td><Link to="/wiki/01">JMT</Link></td>
                    </tr>
                    <tr>
                        <td>02</td>
                        <td>TMI</td>
                    </tr>
                    <tr>
                        <td>03</td>
                        <td>존버</td>
                    </tr>
                    <tr>
                        <td>04</td>
                        <td>탈룰라</td>
                    </tr>
                    <tr>
                        <td>05</td>
                        <td>혼코노</td>
                    </tr>
                    <tr>
                        <td>06</td>
                        <td>괄도 네넴띤</td>
                    </tr>
                    <tr>
                        <td>07</td>
                        <td>갑분싸</td>
                    </tr>
                    <tr>
                        <td>08</td>
                        <td>누물보</td>
                    </tr>
                    <tr>
                        <td>09</td>
                        <td>번달번줌</td>
                    </tr>
                    <tr>
                        <td>10</td>
                        <td>팬아저</td>
                    </tr>
                    <tr>
                        <td>11</td>
                        <td>롬곡</td>
                    </tr>
                    <tr>
                        <td>12</td>
                        <td>이생망</td>
                    </tr>
                    <tr>
                        <td>13</td>
                        <td>법블레스유</td>
                    </tr>
                    <tr>
                        <td>14</td>
                        <td>롬곡옾높</td>
                    </tr>
                    <tr>
                        <td>15</td>
                        <td>별다줄</td>
                    </tr>
                    <tr>
                        <td>16</td>
                        <td>할많하않</td>
                    </tr>
                    <tr>
                        <td>17</td>
                        <td>아아</td>
                    </tr>
                    <tr>
                        <td>18</td>
                        <td>말넘심</td>
                    </tr>
                    <tr>
                        <td>19</td>
                        <td>인구론</td>
                    </tr>
                    <tr>
                        <td>20</td>
                        <td>떡락</td>
                    </tr>
                    <tr>
                        <td>21</td>
                        <td>떡상</td>
                    </tr>
                    <tr>
                        <td>22</td>
                        <td>프로불편러</td>
                    </tr>
                    <tr>
                        <td>23</td>
                        <td>명존쎄</td>
                    </tr>
                    <tr>
                        <td>24</td>
                        <td>기대가 됩니다</td>
                    </tr>
                    <tr>
                        <td>25</td>
                        <td>김칭</td>
                    </tr>
                    <tr>
                        <td>26</td>
                        <td>코와이네</td>
                    </tr>
                    <tr>
                        <td>27</td>
                        <td>갑봉싸</td>
                    </tr>
                    <tr>
                        <td>28</td>
                        <td>사장님임창정</td>
                    </tr>
                    <tr>
                        <td>29</td>
                        <td>싫존주의</td>
                    </tr>
                    <tr>
                        <td>30</td>
                        <td>내또일</td>
                    </tr>
                    <tr>
                        <td>31</td>
                        <td>워라벨</td>
                    </tr>
                    <tr>
                        <td>32</td>
                        <td>댕댕이</td>
                    </tr>
                    <tr>
                        <td>33</td>
                        <td>우유남</td>
                    </tr>
                    <tr>
                        <td>34</td>
                        <td>행복회로</td>
                    </tr>
                    <tr>
                        <td>35</td>
                        <td>전차스</td>
                    </tr>
                    </tbody>
                </table>
            </div>
        );
    }
}
